const ADD_CHAT_LINE = 'ADD_CHAT_LINE';
const DELETE_CHAT_LINE = 'REMOVE_CHAT_LINE';
const ADD_USER = 'ADD_USER';
const DELETE_USER = 'DELETE_USER';
const ADD_CHATROOM = 'ADD_CHAT_ROOM';
const DELETE_CHATROOM = 'DELETE_CHAT_ROOM';
const ADD_USER_TO_CHATROOM = 'ADD_USER_TO_CHATROOM';
const DELETE_USER_FROM_CHATROOM = 'DELETE_USER_FROM_CHATROOM';

const SET_CURRENT_CHATROOM = 'SET_CURRENT_CHATROOM';
const SET_CURRENT_USER = 'SET_CURRENT_USER';

export {ADD_CHAT_LINE, DELETE_CHAT_LINE, ADD_USER, DELETE_USER, ADD_CHATROOM, DELETE_CHATROOM, ADD_USER_TO_CHATROOM, DELETE_USER_FROM_CHATROOM, SET_CURRENT_CHATROOM, SET_CURRENT_USER};
