const ADD_CHAT_LINE = 'ADD_CHAT_LINE';
const DELETE_CHAT_LINE = 'REMOVE_CHAT_LINE';
const ADD_USER = 'ADD_USER';
const DELETE_USER = 'DELETE_USER';

export {ADD_CHAT_LINE, DELETE_CHAT_LINE, ADD_USER, DELETE_USER};
